name: Energia Abierta CL - Bencina En Línea

on:
    push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Instalar Python 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Creating secret JSON
      run: |
        python svBencinaEnLinea.py

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Bencina En Línea"
        branch: main
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        commit_user_email: ianmeza29@gmail.com
        commit_author: DataIntelligence BOT <ianmeza29@gmail.com>
        push_options: '--force'